USE [SPAWebSearchSystemApp]
GO
/**** ---sample data for CustomerOrder table ---****/
truncate table SPAWebSearchSystemApp.dbo.Customer; 

Insert into Customer (name, address, state, city, country, Email) values('David Lee', '20738 84th New Way ', 'WA', 'Olympia', 'USA', 'David933@somesite2.com')
Insert into Customer (name, address, state, city, country, Email) values('Charles Riley', '46696 43th Ave NE ', 'CO', 'Pueblo', 'USA', 'Charles983@webby.com')
Insert into Customer (name, address, state, city, country, Email) values('Ahmed Khan', '40976 48th street ', 'WA', 'Bellevue', 'USA', 'mkhan@newsite2.com')
Insert into Customer (name, address, state, city, country, Email) values('Tim miles', '69th Place SE', 'TN', 'Seymour', 'USA', 'Tim227@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Cody Hadaway', '28131 60th New Way ', 'TN', 'morristown', 'USA', 'cody919@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kevin Bohr', '38072 32th New Way ', 'KS', 'Wichita', 'USA', 'Kevin413@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Howard Smick', '45419 37th New Way ', 'OR', 'Bend', 'USA', 'Howard570@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Tom casey', '48340 87th New Way ', 'WI', 'Edgerton', 'USA', 'Tom975@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('April johannessen', '47377 22th New Way ', 'WA', 'Lakewood', 'USA', 'April52@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Tessa bang', '12424 44th New Way ', 'AL', 'HUNTSVILLE', 'USA', 'Tessa78@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('mark Hogue', '26235 63th New Way ', '', 'horsham', 'United Kingdom', 'mark875@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Billy Dekker', '18935 97th New Way ', 'TX', 'Smithville', 'USA', 'Billy295@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Brian choumiatsky', '40390 93th New Way ', 'AB', 'Drumheller', 'Canada', 'Brian456@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Philip hanson', '13296 99th New Way ', '', 'Granada', 'Spain', 'Philip402@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jonathan Fostino', '2927 74th New Way ', 'MI', 'Ann Arbor', 'USA', 'Jonathan776@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('jason Dahlberg', '15274 110th New Way ', 'TN', 'bean station', 'USA', 'jason728@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ricardo quarm', '25467 63th New Way ', 'FL', 'Largo', 'USA', 'Ricardo972@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Billy Pleasant', '12337 101th New Way ', 'OH', 'Carlisle', 'USA', 'Billy87@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Przemyslaw choumiatsky', '6539 79th New Way ', '', 'boras', 'Sweden', 'Przemyslaw593@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('I. hanson', '43593 64th New Way ', 'NY', 'New York', 'USA', 'I.248@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Louis McGill', '7493 44th New Way ', 'MD', 'Bethesda', 'USA', 'Louis690@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Greg bramley', '31065 49th New Way ', 'BC', 'Aldergrove', 'Canada', 'Greg497@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Guenter Bussing', '38392 59th New Way ', '', 'Hamburg', 'Germany', 'Guenter773@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('William Baily', '11216 23th New Way ', 'TN', 'Knoxville', 'USA', 'William79@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ewan Horan', '41534 110th New Way ', '', 'Inverness', 'United Kingdom', 'Ewan508@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ZAKIR Grote', '46016 64th New Way ', '', 'MADRID', 'Spain', 'ZAKIR369@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Echo Hadley', '29978 39th New Way ', 'CA', 'woodside', 'USA', 'Echo454@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Chrys Sr.', '32526 94th New Way ', 'NV', 'Henderson', 'USA', 'Chrys197@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Carla Johnson', '20044 87th New Way ', 'SD', 'Sturgis', 'USA', 'Carla176@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joseph Anderson', '12319 25th New Way ', '', 'Rehovot', 'Israel', 'Joseph55@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ronald heseman', '35747 84th New Way ', 'WA', 'Sumner', 'USA', 'Ronald321@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ISABEL Saavedra', '41392 11th New Way ', 'CA', 'MALIBU', 'USA', 'ISABEL680@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Juan Shoffner', '31543 96th New Way ', '', 'Sant Feliu de Llobregat', 'Spain', 'Juan222@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Robert ROSSI', '24009 31th New Way ', 'FL', 'Pensacola', 'USA', 'Robert951@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Edmon page', '27185 70th New Way ', 'VA', 'Staunton', 'USA', 'Edmon51@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JAMES Foley', '20767 48th New Way ', 'CA', 'FREMONT', 'USA', 'JAMES441@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Aaron Tollis', '23201 28th New Way ', 'GA', 'nicholson', 'USA', 'Aaron834@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lori Russett', '6594 76th New Way ', 'PA', 'Morgantown', 'USA', 'Lori854@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Romang', '34004 108th New Way ', 'ON', 'Wilberforce', 'Canada', 'David693@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Deborah Cummings', '44234 85th New Way ', 'IL', 'Hoyleton', 'USA', 'Deborah646@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sarah mcbride', '15644 28th New Way ', '', 'Linz', 'Austria', 'Sarah472@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Markus Gillies', '15987 92th New Way ', '', 'västerås', 'Sweden', 'Markus637@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lou Carter', '21523 47th New Way ', 'MB', 'Thompson', 'Canada', 'Lou183@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mark Borch', '35298 77th New Way ', 'IL', 'Roselle', 'USA', 'Mark346@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Arvin Haney', '35025 15th New Way ', 'CA', 'Rowland Heights', 'USA', 'Arvin237@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('vincent Lee', '664 43th New Way ', '', 'ta xbiex', 'Malta', 'vincent641@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Brenda Bauck', '29701 72th New Way ', 'FL', 'Ocoee', 'USA', 'Brenda200@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JR Alley', '22952 38th New Way ', 'NC', 'ATKINSON', 'USA', 'JR683@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Magyar farella', '41998 27th New Way ', '', 'Prague', 'Czech Republic', 'Magyar211@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Larry Voelkert', '22780 76th New Way ', 'KS', 'Syracuse', 'USA', 'Larry822@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Samuel Birkner', '7373 94th New Way ', 'PA', 'Harrisburg', 'USA', 'Samuel53@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Richard foster', '29687 55th New Way ', 'NJ', 'Hackettstown', 'USA', 'Richard501@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('wendy Parmenas', '26835 90th New Way ', 'MD', 'frederick', 'USA', 'wendy431@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('paul Mang', '2913 93th New Way ', '', 'dartford', 'United Kingdom', 'paul169@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('S. Nguyen', '33724 46th New Way ', '', 'CHENNAI', 'India', 'S.47@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Cynthia Alstad', '48182 20th New Way ', '', 'Pembroke', 'Bermuda', 'Cynthia790@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('CHIYO Lee', '23679 30th New Way ', '', 'YOKOHAMA SHI, KANAGAWA KEN', 'Japan', 'CHIYO956@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mary ruan', '37612 99th New Way ', 'MA', 'Rockport', 'USA', 'Mary397@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Robert baker', '2495 40th New Way ', 'SK', 'Hellertown', 'USA', 'Robert632@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Alfano Reinertsen', '48953 58th New Way ', '', 'Taranto', 'Italy', 'Alfano595@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Roy Tilker', '15495 50th New Way ', 'CA', 'San Diego', 'USA', 'Roy979@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Carl Valentine', '18057 34th New Way ', '', 'West Sussex', 'United Kingdom', 'Carl885@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('nelson Luehrs', '20763 73th New Way ', 'AB', 'fort mcmurray', 'Canada', 'nelson243@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Pamela Ward', '37847 51th New Way ', 'TX', 'Houston', 'USA', 'Pamela484@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('GARY Morgan', '48221 24th New Way ', 'NC', 'FAYETTEVILLE', 'USA', 'GARY385@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kevin Arroyo', '30312 29th New Way ', '', 'Melbourne', 'Australia', 'Kevin973@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ashley Duncan', '31534 108th New Way ', 'TX', 'Charleston', 'USA', 'Ashley187@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Stefan Warta', '22401 16th New Way ', '', 'Wees', 'Germany', 'Stefan482@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kevin Reinhardt', '33700 55th New Way ', '', 'New Plymouth', 'New Zealand', 'Kevin404@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dan Shirley', '27211 74th New Way ', 'ID', 'Rathdrum', 'USA', 'Dan89@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Bui', '12270 55th New Way ', 'WI', 'Appleton', 'USA', 'David273@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Perritano', '45643 82th New Way ', 'OH', 'Dover', 'USA', 'David449@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Hongkham Bell', '2534 77th New Way ', 'CA', 'Oakland', 'USA', 'Hongkham214@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('patricia Ayotte', '30248 94th New Way ', 'NM', 'corrales', 'USA', 'patricia790@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('cole parker', '18634 46th New Way ', 'NC', 'Winston Salem', 'USA', 'cole127@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ken Raunde', '36533 107th New Way ', 'CO', 'Arvada', 'USA', 'Ken9@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sean Nielsen', '2135 14th New Way ', 'LA', 'New Iberia', 'USA', 'Sean731@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lavada Diminico', '42960 41th New Way ', 'AR', 'Pocahontas', 'USA', 'Lavada98@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Thomas Fowler', '40378 65th New Way ', 'VA', 'newport news', 'USA', 'Thomas24@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('werner Flux', '16620 50th New Way ', 'IL', 'Bartlet', 'USA', 'werner148@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mike Maag', '40138 97th New Way ', 'MB', 'Winnipeg', 'Canada', 'Mike12@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Anthony Johnson', '6253 109th New Way ', 'WY', 'Gillette', 'USA', 'Anthony272@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Bedford Jarnborg', '2942 96th New Way ', 'NB', 'Lincoln', 'Canada', 'Bedford893@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Eric Thelin', '46821 104th New Way ', 'NH', 'Hudson', 'USA', 'Eric834@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('DOMINICK Osterlund', '16165 83th New Way ', 'NJ', 'LANOKA HARBOR', 'USA', 'DOMINICK475@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Azarizan Klaus', '37252 25th New Way ', '', 'Kuala Terengganu', 'Malaysia', 'Azarizan959@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Abilio Crain', '10283 26th New Way ', 'VA', 'leesburg', 'USA', 'Abilio197@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('naushad Smith', '6478 86th New Way ', '', 'port louis', 'Mauritius', 'naushad81@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Juris Papadimitriou', '5150 76th New Way ', '', 'Riga', 'Latvia', 'Juris134@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mel Heilmann', '13059 101th New Way ', 'NV', 'Pahrump', 'USA', 'Mel628@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('philip Kapsokavadis', '48063 87th New Way ', 'NM', 'albuquerque', 'USA', 'philip480@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JOSE Fountain', '40491 43th New Way ', '', 'CAYEY', 'Puerto Rico', 'JOSE756@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Aj Landers', '25158 59th New Way ', 'NV', 'Vienna', 'USA', 'Aj320@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Scott Shuhail', '23367 85th New Way ', 'TX', 'Dallas', 'USA', 'Scott954@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Rebecca Dietrich', '33926 99th New Way ', '', 'Mersyside', 'United Kingdom', 'Rebecca853@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('REBECCA Setman', '43405 95th New Way ', 'CA', 'Kernville', 'USA', 'REBECCA127@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lisa Rideout', '16340 64th New Way ', 'WA', 'Covington', 'USA', 'Lisa521@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Kruljac', '640 41th New Way ', 'IL', 'Ingleside', 'USA', 'David434@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Judy kozlosky', '22517 85th New Way ', 'CA', 'Escondido', 'USA', 'Judy325@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Robert Jäntti', '4453 80th New Way ', 'CA', 'Del Mar', 'USA', 'Robert979@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('gareth greenwood', '14679 86th New Way ', '', 'skegness lincs', 'United Kingdom', 'gareth514@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('declan Everhart', '36436 107th New Way ', '', 'dublin', 'Ireland', 'declan650@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Niek Brandao', '37478 92th New Way ', '', 'HK Science Park', 'Hong Kong', 'Niek273@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Marsha Misterek', '35744 30th New Way ', 'OR', 'Tiller', 'USA', 'Marsha394@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('GARY Johnson', '45127 79th New Way ', 'NC', 'MONROE', 'USA', 'GARY43@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('shane Moaney', '25747 78th New Way ', 'WA', 'kennewick', 'USA', 'shane655@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ernest Stork', '25148 50th New Way ', 'NM', 'albuquerque', 'USA', 'ernest153@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jose Whipple', '33832 67th New Way ', 'CA', 'King City', 'USA', 'Jose446@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Brian Ezelle', '3991 95th New Way ', '', 'Gisborne', 'New Zealand', 'Brian947@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ken Walker', '5446 71th New Way ', 'AB', 'Claresholm', 'Canada', 'Ken954@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Greg Woodington', '546 38th New Way ', 'OH', 'Mogadore', 'USA', 'Greg529@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jennifer Leggett', '4622 53th New Way ', 'PA', 'Catasauqua', 'USA', 'Jennifer901@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dolores hackett', '35750 31th New Way ', 'PA', 'Philadelphia', 'USA', 'Dolores138@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('kriengkrai Gross', '37158 28th New Way ', '', 'minburi', 'Thailand', 'kriengkrai0@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Delbert Nystrøm', '25442 59th New Way ', 'ME', 'Augusta', 'USA', 'Delbert393@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('toni Coombs', '31810 106th New Way ', 'AL', 'pisgah', 'USA', 'toni688@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Schutt', '45878 38th New Way ', 'VA', 'Midlothian', 'USA', 'David988@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Beau Øien', '26200 110th New Way ', 'WY', 'Sheridan', 'USA', 'Beau31@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Louise Hocking', '35093 45th New Way ', 'QC', 'Pincourt', 'Canada', 'Louise324@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Cruz Martin', '5384 44th New Way ', 'AL', 'Greenville', 'USA', 'Cruz387@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lukas Bauer', '45142 65th New Way ', '', 'Paarl', 'South Africa', 'Lukas131@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('John Blood', '31471 42th New Way ', 'WA', 'Yakima', 'USA', 'John403@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('belpech Joo', '36514 96th New Way ', '', 'auch', 'France', 'belpech770@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jeremey toeller', '22205 24th New Way ', 'TX', 'Willis', 'USA', 'Jeremey426@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Thomas langdon', '14540 81th New Way ', 'LA', 'Bastrop', 'USA', 'Thomas297@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Nicolae Cabrera', '47241 73th New Way ', 'WA', 'Grapeview', 'USA', 'Nicolae995@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mary Taylor', '37101 107th New Way ', 'CA', 'Brentwood', 'USA', 'Mary595@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Daniel mclaughlin', '28538 67th New Way ', 'MA', 'Worcester', 'USA', 'Daniel811@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jeffery Bones', '16312 30th New Way ', 'KY', 'Bonnyman', 'USA', 'Jeffery507@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Michael Nystrøm', '15717 18th New Way ', 'NY', 'Latham', 'USA', 'Michael187@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Christopher Ellis', '9816 19th New Way ', 'MS', 'Pulaski', 'USA', 'Christopher953@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Guiovanny Porter', '13403 88th New Way ', 'NY', 'elmsford', 'USA', 'Guiovanny118@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Donald Mitchell', '21308 65th New Way ', 'FL', 'Interlachen', 'USA', 'Donald493@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jan Lohse', '26513 43th New Way ', 'WA', 'Vashon', 'USA', 'Jan8@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('william Cecil', '2359 102th New Way ', 'VA', 'roanoke', 'USA', 'william258@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Donald Underwood', '42749 88th New Way ', 'NM', 'Santa Fe', 'USA', 'Donald523@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('James Huang', '31589 64th New Way ', 'NY', 'New York', 'USA', 'James589@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jim Mikkelsen', '28297 104th New Way ', '', 'Fareham', 'United Kingdom', 'Jim727@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Steve Johnson', '49822 83th New Way ', 'CA', 'Pacific Palisades', 'USA', 'Steve411@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('patrick Clay', '6709 14th New Way ', 'KS', 'basehor', 'USA', 'patrick223@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Scott GIVENS', '7110 86th New Way ', 'CA', 'Huntington Beach', 'USA', 'Scott655@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('MIGUEL Telephone', '3305 92th New Way ', 'IL', 'NILES', 'USA', 'MIGUEL789@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('arron gallagher', '21277 90th New Way ', '', 'houghton le spring', 'United Kingdom', 'arron884@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Annette Grimes', '19119 60th New Way ', 'NH', 'New London', 'USA', 'Annette704@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('jay Holverson', '30725 89th New Way ', 'CA', 'Nevada City', 'USA', 'jay975@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Anthony Baughn', '38060 79th New Way ', 'CO', 'Parker', 'USA', 'Anthony947@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Fred frandsen', '22117 39th New Way ', 'TX', 'Houston', 'USA', 'Fred0@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Rosemary Reilly', '8536 65th New Way ', 'NH', 'Winnisquam', 'USA', 'Rosemary2@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jeffrey Ayers', '14876 96th New Way ', 'TX', 'Terrell', 'USA', 'Jeffrey446@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kenneth Try', '11150 18th New Way ', 'NY', 'Brooklyn', 'USA', 'Kenneth196@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Charles Nichols', '19328 104th New Way ', 'NY', 'niagara Falls', 'USA', 'Charles310@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Resydson mcnab', '22838 34th New Way ', 'CA', 'South San Francisco', 'USA', 'Resydson657@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kashif Newton', '10615 76th New Way ', '', 'Wolverhampton', 'United Kingdom', 'Kashif473@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JEAN Schultz', '47752 22th New Way ', 'AZ', 'gOLDEN vALLEY', 'USA', 'JEAN863@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('George Bledsoe', '6481 13th New Way ', 'MD', 'Hyattsville', 'USA', 'George207@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Michael Hensley', '1968 95th New Way ', 'NY', 'Port Chester', 'USA', 'Michael415@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jordan Yagil', '9538 84th New Way ', 'ID', 'Moscow', 'USA', 'Jordan275@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('John Wassink', '26439 38th New Way ', 'OH', 'Columbus', 'USA', 'John900@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dale Shelton', '33179 78th New Way ', 'VA', 'Manassas', 'USA', 'Dale545@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Charles BLAKE', '44459 44th New Way ', 'MS', 'Waveland', 'USA', 'Charles359@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Brent Rivers', '19861 38th New Way ', 'BC', 'Coquitlam', 'Canada', 'Brent278@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('geoffrey hoffman', '1746 58th New Way ', 'VA', 'virginia beach', 'USA', 'geoffrey181@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Andrew III', '19483 64th New Way ', 'CT', 'Ridgefield', 'USA', 'Andrew175@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Blanca Badgett', '12791 100th New Way ', '', 'Caguas, PR', 'Puerto Rico', 'Blanca860@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Arlene Lathrop', '1407 81th New Way ', 'TX', 'Houston', 'USA', 'Arlene701@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Michael Coulton', '32636 37th New Way ', 'AR', 'Fairfield Bay', 'USA', 'Michael731@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Steve Voytovich', '25807 72th New Way ', 'ON', 'Toronto', 'Canada', 'Steve411@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joseph Welborn', '40040 16th New Way ', 'VA', 'Montpelier', 'USA', 'Joseph717@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sean Wakelin', '20773 13th New Way ', 'ON', 'Toronto', 'Canada', 'Sean761@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mary williams', '49500 95th New Way ', 'NC', 'vale', 'USA', 'Mary321@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Richard Cox', '39024 21th New Way ', 'WA', 'Duvall', 'USA', 'Richard899@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Geraldine NELSON', '16848 88th New Way ', 'IL', 'Glen Ellyn', 'USA', 'Geraldine729@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('DELMAR corr', '7436 24th New Way ', 'NY', 'NEW YORK', 'USA', 'DELMAR535@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kenneth Green', '26009 28th New Way ', 'VA', 'Suffolk', 'USA', 'Kenneth814@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ANTHONY Steel', '20422 58th New Way ', 'OH', 'cleveland', 'USA', 'ANTHONY363@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Angie Pille', '20694 77th New Way ', 'OK', 'Chandler', 'USA', 'Angie612@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Bruce Hocking', '329 41th New Way ', 'CO', 'Grand Junction', 'USA', 'Bruce755@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Violeta Sartori', '43047 25th New Way ', 'AZ', 'Anthem', 'USA', 'Violeta597@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('thomas Gloria', '40235 57th New Way ', 'MA', 'methuen', 'USA', 'thomas746@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('edward Cunningham', '5409 89th New Way ', 'AZ', 'glendale', 'USA', 'edward19@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('victoria Hemert', '15887 42th New Way ', 'BC', 'vernon', 'Canada', 'victoria501@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Roy III', '15176 12th New Way ', 'MS', 'Collinsville', 'USA', 'Roy143@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Stan Clark', '27367 29th New Way ', 'AZ', 'Scottsdale', 'USA', 'Stan698@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('John Harrington', '16427 21th New Way ', 'CA', 'Healdsburg', 'USA', 'John704@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('kimberly Hennelly', '33746 47th New Way ', 'CO', 'Denver', 'USA', 'kimberly103@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joseph LEER', '36590 84th New Way ', 'CA', 'Santa Rosa', 'USA', 'Joseph441@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Brad Prado', '1605 24th New Way ', 'ON', 'Straffordville', 'Canada', 'Brad14@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Clifford Bobbitt', '44498 66th New Way ', 'TN', 'Morristown', 'USA', 'Clifford427@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Geir Anderson', '21054 13th New Way ', '', 'Skedsmokorset', 'Norway', 'Geir602@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Tommy Robison', '29817 13th New Way ', 'TX', 'Abilene', 'USA', 'Tommy915@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kenneth Large', '15939 43th New Way ', 'FL', 'Cape Coral', 'USA', 'Kenneth861@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mark KEUREN', '47551 20th New Way ', '', 'Cambridge', 'United Kingdom', 'Mark247@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Cassandra Clow', '40270 43th New Way ', 'CO', 'Colorado Springs', 'USA', 'Cassandra805@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ben morskyj', '2273 24th New Way ', 'TX', 'Humble', 'USA', 'Ben159@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Denise Clark', '49544 66th New Way ', 'AK', 'Anchorage', 'USA', 'Denise192@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('lauren Eamens', '5439 63th New Way ', 'FL', 'sebring', 'USA', 'lauren892@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JoMarie McDonald', '2211 65th New Way ', 'AZ', 'Chandler', 'USA', 'JoMarie53@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Nick Matthews', '22221 13th New Way ', 'VA', 'Centreville', 'USA', 'Nick242@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('wariwan Hearn', '18421 27th New Way ', '', 'Samutprakarn', 'Thailand', 'wariwan822@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('david Sanders', '21458 11th New Way ', 'NC', 'morehead city', 'USA', 'david646@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('josh Gutteridge', '631 51th New Way ', 'GA', 'Trenton', 'USA', 'josh678@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('lesley CONDE', '28706 110th New Way ', 'NY', 'mount vernon', 'USA', 'lesley450@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('James davey', '15436 47th New Way ', 'MD', 'Silver Spring', 'USA', 'James433@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('suzie Gilbert', '42046 98th New Way ', 'MA', 'lowell', 'USA', 'suzie560@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dodo Bettridge', '20433 100th New Way ', 'ON', 'Toronto', 'Canada', 'Dodo902@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('TEVI Boykin', '42252 55th New Way ', '', 'Paris', 'France', 'TEVI72@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joe Peach', '7022 108th New Way ', 'TX', 'Kemah', 'USA', 'Joe7@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Markham Bradley', '6541 48th New Way ', 'LA', 'New Orleans', 'USA', 'Markham385@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('todd Schwartz', '39065 58th New Way ', 'PA', 'lower burrell', 'USA', 'todd810@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Zainab Brown', '34849 85th New Way ', 'ON', 'Richmond Hill', 'Canada', 'Zainab359@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('brent Byrnes', '33803 59th New Way ', 'FL', 'ft. myers', 'USA', 'brent2@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ALAN Antal', '42669 51th New Way ', 'NV', 'HENDERSON', 'USA', 'ALAN606@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jules Tulloch', '26700 62th New Way ', 'NV', 'Las Vegas', 'USA', 'Jules908@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Paul Bayer', '20970 108th New Way ', 'GA', 'Lawrenceville', 'USA', 'Paul715@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kenneth Compton', '39691 21th New Way ', 'CA', 'Roseville', 'USA', 'Kenneth998@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Richard Nnaji', '26830 110th New Way ', 'UT', 'Heber city', 'USA', 'Richard47@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Shawn coleman', '26207 84th New Way ', 'SK', 'Saskatoon', 'Canada', 'Shawn167@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jeremie Esdale', '19916 77th New Way ', 'NB', 'Shediac', 'Canada', 'Jeremie182@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Paige Addison', '8708 34th New Way ', 'MT', 'Bigfork', 'USA', 'Paige937@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Stephanie Hudson', '45498 87th New Way ', 'MD', 'Manchester', 'USA', 'Stephanie712@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Scott Farnham', '36841 100th New Way ', 'NC', 'Wilmington', 'USA', 'Scott843@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Kyle Sandstrom', '33541 104th New Way ', 'SC', 'York', 'USA', 'Kyle665@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Shane Lines', '6091 109th New Way ', 'AE', 'APO', 'USA', 'Shane570@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Robert Hansen', '3117 34th New Way ', 'FL', 'Fort Laudrdale', 'USA', 'Robert983@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Yumiko CONNOLLY', '2990 15th New Way ', 'WA', 'Seattle', 'USA', 'Yumiko237@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('ray Kinahan', '24624 74th New Way ', 'AZ', 'mesa', 'USA', 'ray88@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('KEITHANIEL Baratz', '706 49th New Way ', 'GA', 'MORROW', 'USA', 'KEITHANIEL78@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Richard Kluth', '3136 20th New Way ', 'AZ', 'Cottonwood', 'USA', 'Richard66@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Lisa swett', '3788 108th New Way ', 'KY', 'mayking', 'USA', 'Lisa215@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Susie Serata', '30929 80th New Way ', '', 'Wairoa', 'New Zealand', 'Susie132@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ken EPPINGER', '18618 81th New Way ', 'FL', 'Spring Hill', 'USA', 'Ken465@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jorge LaFauci', '29216 60th New Way ', 'MA', 'S. Lancaster', 'USA', 'Jorge665@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Studio Leary', '46692 67th New Way ', '', 'Ciampino', 'Italy', 'Studio246@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Hendrix robaina', '23196 29th New Way ', 'IL', 'Oak Park', 'USA', 'Hendrix611@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Phillip Richmond', '13342 77th New Way ', 'GA', 'Lilburn', 'USA', 'Phillip788@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Casey zubowicz', '14564 45th New Way ', 'LA', 'West Monroe', 'USA', 'Casey799@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dan Yamaoka', '40401 52th New Way ', 'TX', 'Fort Worth', 'USA', 'Dan691@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('richard Robbie', '48257 16th New Way ', 'MO', 'st.louis', 'USA', 'richard3@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('lee Santi', '11256 69th New Way ', 'TX', 'highland village', 'USA', 'lee976@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Gary Burnett', '30236 100th New Way ', 'AZ', 'Tucson', 'USA', 'Gary428@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joel Rolnick', '26590 11th New Way ', 'NC', 'Rocky Mount', 'USA', 'Joel357@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jamie Maduro', '47550 106th New Way ', 'NH', 'Warner', 'USA', 'Jamie360@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Heidi Piercy', '12880 59th New Way ', 'ON', 'Englehart', 'Canada', 'Heidi496@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Wanda Leonard', '15397 40th New Way ', 'TX', 'Abilene', 'USA', 'Wanda851@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sotiris Dailey', '49900 37th New Way ', '', 'Johannesburg', 'South Africa', 'Sotiris967@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Amanda Schnuir', '34621 29th New Way ', 'MT', 'Denton', 'USA', 'Amanda319@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Diane staig', '23735 78th New Way ', 'OH', 'Aurora', 'USA', 'Diane950@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Willie pollett', '12058 16th New Way ', 'KY', 'Lexington', 'USA', 'Willie233@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Bonita McLean', '8514 40th New Way ', '', 'San Juan', 'Puerto Rico', 'Bonita20@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('kevin Hugley', '3498 95th New Way ', 'ME', 'saco', 'USA', 'kevin10@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Douglass piper', '7952 75th New Way ', 'WA', 'Lacey', 'USA', 'Douglass582@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('James tedeschi', '23787 39th New Way ', 'NC', 'morehead city', 'USA', 'James381@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Arica Ravlich', '39074 35th New Way ', 'PA', 'Hopewell', 'USA', 'Arica108@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Eddie brooks', '37091 69th New Way ', 'FL', 'Dania Beach', 'USA', 'Eddie2@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mark Bennett', '8422 65th New Way ', 'GA', 'Warner Robins', 'USA', 'Mark205@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Roosevelt McGarvey', '47090 32th New Way ', 'GA', 'Nicholls', 'USA', 'Roosevelt660@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Richard Rapzo', '42451 55th New Way ', 'SC', 'Warrenville', 'USA', 'Richard715@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('lukas Wood', '34594 55th New Way ', 'QC', 'gatineau', 'Canada', 'lukas555@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Len Basso', '7572 89th New Way ', 'ON', 'Hastings', 'Canada', 'Len976@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Jose Stoica', '24902 53th New Way ', 'CA', 'Los Angeles', 'USA', 'Jose656@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Tricia Victor', '18622 20th New Way ', 'BC', 'chemainus', 'Canada', 'Tricia970@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Betsey McNamara', '12638 14th New Way ', 'FL', 'West Palm Beach', 'USA', 'Betsey50@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Steven Schutz', '6945 92th New Way ', 'CO', 'Westminster', 'USA', 'Steven255@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('sally Fowler', '14790 40th New Way ', '', 'young', 'Australia', 'sally22@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Dilip Bombardier', '36825 19th New Way ', '', 'Margao', 'India', 'Dilip574@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Karen SATO', '22691 105th New Way ', '', 'East Perth', 'Australia', 'Karen71@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Elmer Koopman', '37537 13th New Way ', 'MD', 'Hyattsville', 'USA', 'Elmer152@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Debbi Spitz', '44473 68th New Way ', 'UT', 'Saratoga Springs', 'USA', 'Debbi676@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('jack Casella', '43662 16th New Way ', 'NJ', 'Fairfield', 'USA', 'jack305@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Royce Goodson', '9941 29th New Way ', 'UT', 'hurricane', 'USA', 'Royce702@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ted McBride', '38610 36th New Way ', 'MI', 'South Haven', 'USA', 'Ted691@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('David Algie', '28861 80th New Way ', 'NC', 'Wilmington', 'USA', 'David117@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Joseph bath', '46185 96th New Way ', 'PA', 'Philadelphia', 'USA', 'Joseph688@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Andrew lazzari', '33906 91th New Way ', 'UT', 'Bountiful', 'USA', 'Andrew628@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Cody Kenny', '5523 16th New Way ', 'CA', 'Cathedral City', 'USA', 'Cody791@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Pawel Thompson', '28691 36th New Way ', 'IL', 'Plainfield', 'USA', 'Pawel978@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Mr Gricar', '35482 38th New Way ', '', 'Peterborough', 'United Kingdom', 'Mr380@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Glenn wilde', '667 66th New Way ', 'TX', 'Humble', 'USA', 'Glenn247@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JAMES Reinoehl', '39948 66th New Way ', 'NM', 'ELEPHANT BUTTE', 'USA', 'JAMES595@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Michael Ray', '33553 74th New Way ', 'NY', 'APO, AE', 'USA', 'Michael126@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('sky Chavis', '42635 75th New Way ', '', 'jerusalem', 'Israel', 'sky310@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sandra Davidge', '13343 66th New Way ', 'NC', 'Winnabow', 'USA', 'Sandra998@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sharon Borton', '25982 18th New Way ', 'AZ', 'Bullhead City', 'USA', 'Sharon124@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Bud hosoda', '38974 23th New Way ', 'FL', 'Naples', 'USA', 'Bud48@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('James samuel', '27492 62th New Way ', 'TX', 'Killeen', 'USA', 'James20@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('John Angelo', '20682 79th New Way ', '', 'Canberra ACT', 'Australia', 'John48@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Katje norris', '3605 47th New Way ', 'NM', 'Edgewood', 'USA', 'Katje827@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Ari Braker', '14271 24th New Way ', '', 'Hamina', 'Finland', 'Ari853@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Thomas Smith', '47281 99th New Way ', 'OR', 'Gresham', 'USA', 'Thomas919@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('John pawlak', '2144 59th New Way ', 'CA', 'Lake Forest', 'USA', 'John783@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('frank Porter', '39665 29th New Way ', 'NY', 'saratoga springs', 'USA', 'frank34@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Don Ward', '19331 33th New Way ', '', 'Mosgiel', 'New Zealand', 'Don979@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('gina Cromwell', '19560 103th New Way ', 'CA', 'hayward', 'USA', 'gina263@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('E poole', '30995 104th New Way ', 'FL', 'PalmBeach  Gardens', 'USA', 'E77@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Yongyuth allen', '35357 24th New Way ', 'CA', 'San Marcos', 'USA', 'Yongyuth148@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('JOSEPH Beamer', '21290 92th New Way ', 'NM', 'ALBUQUERQUE', 'USA', 'JOSEPH80@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('soumendra viders', '17241 61th New Way ', '', 'croydon', 'United Kingdom', 'soumendra207@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('William Groden', '36859 56th New Way ', 'KY', 'OWENTON', 'USA', 'William288@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Sara McIntosh', '5145 73th New Way ', 'MO', 'Kansas City', 'USA', 'Sara792@new1site2.com')
Insert into Customer (name, address, state, city, country, Email) values('Gail Klemm', '3471 20th New Way ', 'NC', 'Beaufort', 'USA', 'Gail590@new1site2.com')

---sample data for CustomerOrder table ---
truncate table product
 insert into Product(Name, Price, Picture) values('B-complex',19.95,'B-complex_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Calcium',9.95,'calcium_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Flaxseed-oil',29.95,'flaxseed-oil_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Iron',39.95,'iron_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Magnesium',19.95,'magnesium_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Multi-vitamin',49.95,'multi-vitamin_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Vitamin-A',59.95,'vitamin-A_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Vitamin-C',19.95,'vitamin-C_600px-300x300.png')
 insert into Product(Name, Price, Picture) values('Vitamin-D',29.95,'vitamin-D_600px-300x300.png')


 ---sample data for CustomerOrder table ---
truncate table CustomerOrder
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(1,'2/1/2016', 33.98)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(2,'6/6/2016', 44.54)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(2,'3/1/2017', 35.34)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(3,'3/1/2017', 51.14)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(3,'3/2/2017', 35.11)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(4,'3/3/2017', 54.21)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(4,'3/4/2017', 22.12)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(5,'3/5/2017', 64.34)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(1,'3/6/2017', 44.11)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(6,'3/7/2017', 34.21)
insert into CustomerOrder(CustomerId, OrderDate, TotalUSD) values(7,'3/8/2017', 135.12)
 
 ---sample data for OrderProduct table --
truncate table OrderProduct
insert into OrderProduct(OrderId, ProductId, Quantity) values(1,2,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(1,1,2)
insert into OrderProduct(OrderId, ProductId, Quantity) values(2,9,4)
insert into OrderProduct(OrderId, ProductId, Quantity) values(3,2,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(4,6,2)
insert into OrderProduct(OrderId, ProductId, Quantity) values(5,6,3)
insert into OrderProduct(OrderId, ProductId, Quantity) values(6,4,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(7,8,1) 
insert into OrderProduct(OrderId, ProductId, Quantity) values(8,1,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(8,2,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(8,3,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(8,4,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(8,5,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(9,7,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(10,5,1)
insert into OrderProduct(OrderId, ProductId, Quantity) values(11,4,1)